### ISSUE TITLE
Configure logic issue

### ISSUE THREAD

**Issue by invisiblearts** [HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-w2xc#1]
When w2xc is not installed, the error returned is vapoursynth check failure.

**Comment by HolyWu** [comment]
Thanks for the report. Does 6cc1da611d15a6a51341dd5f4c3b80661fe9af10 fix it?

**Comment by invisiblearts** [comment]
6cc1da6 works well.. However, 
`warning: pkg-config or pc files not found, lib detection may be inaccurate.`
always appears(also in the former commit), even if `PKG_CONFIG_PATH` is set.(At least on OS X)

**Comment by HolyWu** [comment]
Unfortunately I really don't know what should I do to fix that.

**Comment by invisiblearts** [comment]
w2xc itself does not provide pc files at all, and thus pkg-config will always fail..
By default the library to link against is always libw2xc.*, so the pkg-config part should be removed from the configure script.

**Comment by HolyWu** [comment]
Thanks for your explanation. Does 4fdc7ae67c4f1eb2e5ca31d5cb18bc932213bd57 work as expect?

**Comment by invisiblearts** [comment]
Yes, works fine.
