### ISSUE TITLE
Loading other models

### ISSUE THREAD

**Issue by theChaosCoder** [HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-w2xc#10]
A user in doom9 (https://forum.doom9.org/showthread.php?p=1861431#post1861431) asked if other models like https://github.com/nagadomi/waifu2x/tree/master/models/cunet/art could be added.

Because the path for a model is currently hardcoded, I was thinking that if a user-defined var (like model_path or custom_model) could be added to make the plugin more flexible? Is such thing possible?

**Comment by HolyWu** [comment]
Unfortunately that won't work. The underlying code needs to do proper processing as well since the framework is different. Specifying an incompatible model will simply make the program crash.
