### ISSUE TITLE
[Feature Request] Add support for the user to provide a custom mask

### ISSUE THREAD

**Issue by kriNon** [HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-w2xc#11]
Hey,
I'm looking into using waifu2x for antialiasing purposes, and as such I only require the lineart to be processed. As such I was thinking, maybe it would be possible to speed up waifu2x by only calculating the new values required, and not processing the rest of the image. It could also be used in a similar way to the pscrn variable in nnedi3, allowing for faster processing.

**Comment by HolyWu** [comment]
I'm afraid that it's not possible as the feature can't be implemented alone in this filter. The underlying w2xc library need to do the necessary changes.
