### ISSUE TITLE
Video Processing strange output

### ISSUE THREAD

**Issue by xmaayy** [HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-w2xc#12]
Script
```
import vapoursynth as vs
core = vs.get_core()
core.std.LoadPlugin(path="/usr/local/lib/libffms2.so") 
core.std.LoadPlugin(path="/usr/local/lib/libwaifu2x-w2xc.so") 
core.std.LoadPlugin(path="/usr/local/lib/libfmtconv.so") 
c= core.ffms2.Source(source='~/Videos/DB/EPS/title_t07.mkv') 
c = core.fmtc.bitdepth(clip=c, bits=32)
c = core.w2xc.Waifu2x(clip=c, noise=1, scale=1)
c.set_output()
```
Setting output before the w2xc step:
![without](https://user-images.githubusercontent.com/21166352/58423214-8b13ed00-8062-11e9-9644-130b95b4de54.png)
Setting the output after the w2xc step:
![green](https://user-images.githubusercontent.com/21166352/58423233-9535eb80-8062-11e9-9b4e-a9331cbeaf29.png)

Its not always completely green, sometimes it looks like a damaged VHS tape where it looks like
![bad](https://user-images.githubusercontent.com/21166352/58423312-c6aeb700-8062-11e9-80d9-c3e07d0ba738.png)
![badv2](https://user-images.githubusercontent.com/21166352/58423358-e5ad4900-8062-11e9-99cc-5cc9b7351bea.png)

Everything was compiled from source (Vapoursynth, w2xc, this package) on Ubuntu 18.04. No shortcuts were taken, and the output of the w2xc (the converter this uses) works perfectly.

**Comment by HolyWu** [comment]
The Y (luma only) model is not supported anymore and is dropped now.
