### ISSUE TITLE
[Feature Request] waifu2x-ncnn-vulkan of vapoursynth?

### ISSUE THREAD

**Issue by fuchanghao** [HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-w2xc#13]
From a Chinese developer:https://zhuanlan.zhihu.com/p/61576454

project page:https://github.com/nihui/waifu2x-ncnn-vulkan

waifu2x-ncnn-vulkan support cunet and upconv 7 on AMD/intel GPUs.

**Comment by HolyWu** [comment]
https://github.com/Nlzy/vapoursynth-waifu2x-ncnn-vulkan
