### ISSUE TITLE
Failed to build with latest w2xc.

### ISSUE THREAD

**Issue by fitu996** [HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-w2xc#14]
```
[1/2] Compiling C++ object 'waifu2x-w2xc@sha/Waifu2x-w2xc_Waifu2x-w2xc.cpp.o'.
FAILED: waifu2x-w2xc@sha/Waifu2x-w2xc_Waifu2x-w2xc.cpp.o 
c++ -Iwaifu2x-w2xc@sha -I. -I../waifu2x-w2xc -I/usr/include/vapoursynth -fvisibility=hidden -flto -fdiagnostics-color=always -DNDEBUG -pipe -D_FILE_OFFSET_BITS=64 -std=c++14 -ffast-math -mfpmath=sse -msse2 -march=native -mtune=native -O2 -fstack-protector-strong -fno-plt -D_FORTIFY_SOURCE=2 -fPIC -MD -MQ 'waifu2x-w2xc@sha/Waifu2x-w2xc_Waifu2x-w2xc.cpp.o' -MF 'waifu2x-w2xc@sha/Waifu2x-w2xc_Waifu2x-w2xc.cpp.o.d' -o 'waifu2x-w2xc@sha/Waifu2x-w2xc_Waifu2x-w2xc.cpp.o' -c ../waifu2x-w2xc/Waifu2x-w2xc/Waifu2x-w2xc.cpp
../waifu2x-w2xc/Waifu2x-w2xc/Waifu2x-w2xc.cpp: In function \u2018bool filter(const VSFrameRef*, VSFrameRef*, Waifu2xData*, const VSAPI*)\u2019:
../waifu2x-w2xc/Waifu2x-w2xc/Waifu2x-w2xc.cpp:71:9: error: \u2018w2xconv_convert_rgb_f32\u2019 was not declared in this scope
   71 |     if (w2xconv_convert_rgb_f32(d->conv,
      |         ^~~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
```

**Comment by HolyWu** [comment]
I'm thinking that this filter is obsolete and of little use nowadays. For NVIDIA there are both caffe and ncnn-vulkan. For AMD and Intel there is ncnn-vulkan. They all run significantly faster than w2xc. Besides, w2xc only supports old vgg_7 model, while the others support better upconv_7 and cunet models.

**Comment by reketoUMA** [comment]
Well, I built "VapourSynth-Waifu2x-w2xc" with ninja on macOS 10.15.3. Just followed compilation steps in README. It also returned "w2xconv_convert_rgb_f32-not-declared" error.

BTW, waifu2x-converter-cpp had built successfully on my Mac.

**Comment by HolyWu** [comment]
This plugin is considered obsolete for reasons mentioned above. Just use https://github.com/Nlzy/vapoursynth-waifu2x-ncnn-vulkan then.

**Comment by sl1pkn07** [comment]
well.... https://github.com/Nlzy/vapoursynth-waifu2x-ncnn-vulkan/issues/1

**Comment by fitu996** [comment]
This filter may be the only filter that has pure CPU processing support. So sorry to see it is obsolete. But why close this issue? This issue may inform other users to turn to new solutions rather than this obsolete one.

**Comment by HolyWu** [comment]
The notification was already on the top of the main page.
