### ISSUE TITLE
Any guide on how to

### ISSUE THREAD

**Issue by YukiSakuma** [HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-w2xc#4]
So it seems this one can be used for videos and I am really interested to upscale videos especially anime but I don't know how to do it. I am looking for a detailed yet simple guide on how to do it thanks!~

**Comment by HolyWu** [comment]
It's simply a plugin of VapourSynth. The plugin itself is quite straightforward to use. If you haven't installed VapourSynth yet, you may want to read the docs at http://www.vapoursynth.com/ first.

**Comment by YukiSakuma** [comment]
Sorry for late response I did follow the instructions on how to install vapoursynth and verifying it with python but I am having a hard time how to install step by step the actual waifu2x filter and how to use it preferrably I would like to use the waifu2x caffe for vapoursynth
