### ISSUE TITLE
How to utilize multiple GPU?

### ISSUE THREAD

**Issue by tleydxdy** [HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-w2xc#6]
I have two AMD GPU in my system, seem like only one of then was utilized. I remember OpenCL can use muti-GPU natively? Or otherwise, how can I manually select which GPU it runs on?

**Comment by HolyWu** [comment]
You can manually select the device via the `processor` parameter.

**Comment by tleydxdy** [comment]
sorry, my bad. Didn't saw it.
