### ISSUE TITLE
Fail to build

### ISSUE THREAD

**Issue by marillat** [HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-w2xc#9]
Latest version 7 fail to build with

```
Waifu2x-w2xc/Waifu2x-w2xc.cpp: In function ‘void waifu2xCreate(const VSMap*, VSMap*, void*, VSCore*, const VSAPI*)’:
Waifu2x-w2xc/Waifu2x-w2xc.cpp:253:70: error: cannot convert ‘size_t*’ {aka ‘long unsigned int*’} to ‘int*’
     const W2XConvProcessor * processors = w2xconv_get_processor_list(&numProcessors);
                                                                      ^~~~~~~~~~~~~~
In file included from Waifu2x-w2xc/Waifu2x-w2xc.cpp:31:
/usr/include/w2xconv.h:152:79: note:   initializing argument 1 of ‘const W2XConvProcessor* w2xconv_get_processor_list(int*)’
 W2XCONV_EXPORT const struct W2XConvProcessor *w2xconv_get_processor_list(int *ret_num);
```
Maybe this patch fix this issue ?
```
--- a/Waifu2x-w2xc/Waifu2x-w2xc.cpp
+++ b/Waifu2x-w2xc/Waifu2x-w2xc.cpp
@@ -249,7 +249,7 @@ static void VS_CC waifu2xCreate(const VS
 
     const bool log = !!vsapi->propGetInt(in, "log", 0, &err);
 
-    size_t numProcessors;
+    int numProcessors;
     const W2XConvProcessor * processors = w2xconv_get_processor_list(&numProcessors);
 
     if (d.noise < 0 || d.noise > 3) {
```

**Comment by HolyWu** [comment]
I guess you are not using DeadSix27's fork of w2xc? See https://github.com/HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-w2xc/commit/fcf264a78c18be6418fd2ebcd4ce082ea303161c.

**Comment by marillat** [comment]
@HolyWu I'm using the latest release tarball version 7 which include fcf264a
 Environment Linux GCC 8.2.0 amd64 architecture

**Comment by HolyWu** [comment]
You misunderstood me. I mean using the fork of https://github.com/DeadSix27/waifu2x-converter-cpp instead of https://github.com/tanakamura/waifu2x-converter-cpp.

**Comment by marillat** [comment]
OK, I understand. waifu2x-converter-cpp 5.2 from DeadSix27 is enough or I need to use master ?

**Comment by HolyWu** [comment]
There are quite a few commits after 5.2 release so I guess it's better to use the master.

**Comment by marillat** [comment]
OK. Thanks for your help and sorry for the false bug report;

**Comment by marillat** [comment]
FYI, waster is mandatory.
